model_name_or_path: "llm-stacking/StackLLM_3B_300BToken"
dataset: "../../data/preprocessed/simp_wiki_auto_new.json"
dataset_format: "input-output"
output_dir: "../models/stack_3b_m1"
checkpoint_dir: "../models/stack_3b_m1"
trust_remote_code: true
max_length: 512
max_eval_samples: 256
overwrite_output_dir: true
do_train: true
do_eval: true
do_predict: false
evaluation_strategy: "steps"
per_device_train_batch_size: 1
gradient_accumulation_steps: 8  # Increase to maintain the effective batch size
per_device_eval_batch_size: 1
eval_accumulation_steps: 8
dataloader_num_workers: 4
learning_rate: 2e-5
weight_decay: 0.0
num_train_epochs: 3
max_steps: -1
lr_scheduler_type: "constant"
logging_steps: 200
save_strategy: "epoch"
save_steps: 0
save_total_limit: 2
eval_steps: 1000
seed: 42
report_to: wandb
fp16: true
dataloader_pin_memory: true
gradient_checkpointing: true
source_max_len: 512
target_max_len: 128
task: 'Simp'
predict_with_generate: false
train_on_source: false